[book]
authors = ["Quentin Fortier"]
language = "en"
multilingual = false
src = "src"
title = "Informatique commune 2ème année"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/fortierq/ipt2"

[output.html.print]
enable = false
